service:
  name: sls-vscode-debug-ts

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 1234
    printOutput: true

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
